### PR TITLE
[enhancement] optimize build-pipe image

### PR DESCRIPTION
**Pull request by eifrach**
# Description
reopen PR #171 
This PR is enhancement for the build-pipe image

1. add layering for increment builds / push / pull
2. removing duplicated downloads for `kubectl`
3.  add `/var/cache/yum` delete after installation

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [X] I have performed a self-review of my own code
- [X] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [X] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [X] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [X] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by alknopfler** [comment]
@eifrach please rebase solving conflicts to be merge

**Comment by alknopfler** [comment]
we needed to merge the other one before ;)

**Comment by eifrach** [comment]
@alknopfler done

**Comment by alknopfler** [comment]
all tests passed

**Pull request merged**
