### PR TITLE
revert: Revert signatures workaround

### LINKED ISSUE #354: Undo override from bz 2073197
Revert change in #353 once BZ https://bugzilla.redhat.com/show_bug.cgi?id=2073197#c19 has been fixed

Also revert #436

Relevant: https://github.com/openshift/machine-config-operator/issues/1349

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Revert signatures workaround once that BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2073197#c19 has been fixed and released

Fixes #354

### CODE REVIEW

**Review by alknopfler — APPROVED** [review]
LGTM

**Comment by flaper87** [comment]
UI image build failure! Skipping and merging

**Comment by iranzo** [comment]
This was supposed to be merged ONCE the BZ linked has been merged in dowsntream, currently it's in ON_QA as described in the PR:

image

And current BZ status:


image

**Comment by flaper87** [comment]
> This was supposed to be merged ONCE the BZ linked has been merged in dowsntream, currently it's in ON_QA as described in the PR:
> 
> image
> 
> And current BZ status:
> 
> image

The PR message was not clear to me. NExt time, please, mark the PR as WIP/Draft and put it on hold. That's what all these things are for.

**Pull request merged**
