### PR TITLE
MGMT-10576: Missing clear indication for starting/ending each task

### LINKED ISSUE #420: invalid input params for task contrib-gpu-operator: didn't need these params but they were provided anyway: [debug]
Some CI runs like:

https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/runs/6931499819?check_suite_focus=true#step:5:61

Give this message, opening as reminder to investigate

### PR DESCRIPTION
**Pull request by eifrach**
Signed-off-by: eifrach <eifrach@redhat.com>

# Description

- adding info state on end of each task
- adding debug option for more information three oprions
   - `true` shows start /end of script
   - `verbose` sets -x
   -  `vvv` sets -xvu 

Fixes #420 

## Type of change

Please select the appropriate options:

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update
- [ ] This change is a documentation update

### CODE REVIEW

**Comment by iranzo** [comment]
Edited description to indicate that it will solve #420 (which was caused by this PR too ;-) as the parameters loaded in the pipeline were not the one in another PR

**Comment by iranzo** [comment]
@eifrach maybe it's worth to split this into two... one for the start/end and another one to do the bootstrap on each CI run...  as if this falls into another host, it might cause the same issue, having a different one, it will help with other pr's too meanwhile this one is merged

**Comment by eifrach** [comment]
> mean for this PR as this looks perfect the way it is, but

well i can also add timestamps if needed.
@iranzo i dont like this solution also, it too messy in my opinion 

i dont see the added value of splitting into two PR's can you give more details ?

**Comment by iranzo** [comment]
> > mean for this PR as this looks perfect the way it is, but
> 
> well i can also add timestamps if needed. @iranzo i dont like this solution also, it too messy in my opinion
> 
> i dont see the added value of splitting into two PR's can you give more details ?

Each time this PR is executed on a host, the host gets the pipeline update... effective breaking all other PR's executions while this one is not merged as new parameters are added that other pr's are not using. Breaking each PR by one functional change we can add the 'redeploy pipelines on each pipeline run' that will allow this and further pr's to deploy what they expect to have for running

**Comment by iranzo** [comment]
image

**Comment by eifrach** [comment]
> image

Running now CI #423

**Comment by eifrach** [comment]
this is too out dated -- new to re-factor this

closing this PR

**Pull request closed without merging**
