### PR TITLE
NO_ISSUE: Allow to set custome DNS

### PR DESCRIPTION
**Pull request by flaper87**
Signed-off-by: Flavio Percoco <flavio@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Before we move forward with this, there are a few things to consider: 

1. We can allow users to completely overwrite the network configs. This will provide all the flexibility needed but it opens the edgecluster deployment to different network configurations,  which may result in broken deployments.
2. Modifying the deployment NMStateConfig does not change the final config that we inject in NMState Operator, which makes implementing this more complex.
3. If we allow for an NMStateConfig to be provided, we ought to make sure that the provided configs are merged with the ones generated by ZTPFW. Otherwise, users would have to provide the *whole* nmstate config. 
4. We extract some information from the edgecluster file that may not be aligned with the nmstate config overrides.

The simplest solution may be to just allow for specific settings to be overwritten (like DNS), rather than dealing with the whole NMStateConfig. The downside is that this option is quite limiting, and sooner or later we will be asked for more complex scenarios to be supported. 

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Review by eifrach — APPROVED** [review]
Lgtm

**Comment by eifrach** [comment]
I think we should avoid networking config on the edge cluster, the network customization should be only in the UI ( wizard ) 
maybe we can create some kind of re-running of the wizard ( like a checkbox that keeps the deployment after changes is applied )

**Comment by danielchg** [comment]
I think we should allow specific settings to be modified, as @flaper87 said i.e. the DNS. For sure that will be more asks, but at least we will have control over those, because the edgecluster can be broken if the modification of the NMstate Operator change something that affect the operation of the OCP itself. 
There are already some specific use cases that need to create a bridge interface, but currently that is not supported by the NMState Operator, so we should be asked to bring a solution for those cases and ensure the deployed edgecluster will be 100% funtional.

**Comment by flaper87** [comment]
@eifrach @danielchg one thing to keep in mind is that this intends to allow for customizations in the deployment network, not the edge cluster. Note how the changes are done during the `render_edgecluster` step and not the NMState Operator configurations.

**Pull request closed without merging**
