### PR TITLE
The timeout for edgeclusters pipeline run adjusted to 7 hours

### PR DESCRIPTION
**Pull request by achuzhoy**
Signed-off-by: Alexander Chuzhoy <achuzhoy@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by achuzhoy** [comment]
cc @alknopfler

**Review by flaper87 — APPROVED** [review]
/lgtm

**Review by alknopfler — APPROVED** [review]
LGTM

**Comment by achuzhoy** [comment]
@flaper87 do we want to merge this one?

**Comment by flaper87** [comment]
> @flaper87 do we want to merge this one?

It scares me to increase the timeout this much. It sounds like we will lose focus and not optimize to improve the deployment time. 

Even with TPM enabled, we should not need 7h to deploy, it's A LOT of time. 

Am I missing something?

**Comment by achuzhoy** [comment]
> > @flaper87 do we want to merge this one?
> 
> It scares me to increase the timeout this much. It sounds like we will lose focus and not optimize to improve the deployment time.
> 
> Even with TPM enabled, we should not need 7h to deploy, it's A LOT of time.
> 
> Am I missing something?

Right.
Maybe things will look differently once bigger disks are installed in the testbeds.
Without the mirroring for edge it takes a fraction of that time:
```
[kni@provisionhost-0-0 ocs-ci]$ tkn pr ls
NAME                                          STARTED      DURATION   STATUS
deploy-ztp-edgeclusters-connected-run-9k2dw   2 days ago   1h11m0s    Succeeded
deploy-ztp-hub-run-tkmpf                      2 days ago   33m12s     Succeeded
deploy-ztp-hub-run-x6bw6                      2 days ago   1h46m47s   Failed

```

**Comment by achuzhoy** [comment]
Closing as this is no longer required.

**Pull request closed without merging**
