### PR TITLE
Add mandatory root_disk

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Adds mandatory root_disk configuration to the examples, documentation and preflight verification

### CODE REVIEW

**Review by jparrill — DISMISSED** [review]
LGTM

**Comment by jparrill** [comment]
LGTM

**Review by jparrill — APPROVED** [review]

**Review by jparrill — DISMISSED** [review]

**Review by alknopfler — DISMISSED** [review]
LGTM

**Review by jparrill — DISMISSED** [review]
LGTM

**Review by alknopfler — APPROVED** [review]

**Review by alknopfler — APPROVED** [review]

**Review by alknopfler — APPROVED** [review]

**Comment by iranzo** [comment]
Merging as the part for the disk validation is done at the beginning of the pipe

**Pull request merged**
