### PR TITLE
NO-ISSUE: ci: Run a nightly build on main

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Nightly build of the branch

### CODE REVIEW

**Comment by eifrach** [comment]
do we have a dedicated host for this ?

/lgtm

**Comment by iranzo** [comment]
It will run on any of the available CI-pool hosts as any other job

**Comment by flaper87** [comment]
I'm a bit confused by the action definition. 

- Is this going to run only for PRs?
- Will it run on main?
- According to the output of today's call, we should have a pipeline that will run the e2e test (we can start with just edgecluster for now), and then we should have a build and push to latest. 

Thanks for picking this task up, let's have a jira ticket to workout all the details. :pray:

**Comment by iranzo** [comment]
> I'm a bit confused by the action definition.
> 
> * Is this going to run only for PRs?
> * Will it run on main?
> * According to the output of today's call, we should have a pipeline that will run the e2e test (we can start with just edgecluster for now), and then we should have a build and push to the latest.
> 
> Thanks for picking this task up, let's have a Jira ticket to work out all the details. pray

This only covers the 'edgecluster'... that is... is running our actual CI on daily basis, and it runs out of main and for PR's, as you can see in the triggers, there are several:

- cron
- pr, etc
the newly added one is the cron one, nothing else changed.

If a new e2e is configured, it should inherit the 'cron' trigger for running daily

**Review by eifrach — APPROVED** [review]

**Comment by flaper87** [comment]
/hold

Please, refer to the open Jira ticket for these tasks

**Comment by flaper87** [comment]
@iranzo let's move this one forward. Can you reference the related jira in the subject? please :)

**Pull request closed without merging**
