### PR TITLE
re-enabling UI testing

### PR DESCRIPTION
**Pull request by eifrach**
Signed-off-by: eifrach <eifrach@redhat.com>

# Description

enabling UI failure on build

### CODE REVIEW

**Comment by iranzo** [comment]
lgtm, but we need generation to be fixed before moving forward :-)

**Comment by mareklibra** [comment]
The `make ui-image-ci` **is passing locally**. When executed within CI, we are facing
- random SIGSEGV nodejs issue when running eslint
  - just flaky, re-execution helps. We can dig deeper but I can expect a lot of effort with limited outcome here. Or we can hope in a fix in future versions of either nodejs or eslint (which I will update in a follow-up)
- external registry issue - requests on packages in the yarnpkg registry return HTTP 500 randomly (varies among attempts)

**Comment by mareklibra** [comment]
**A hope** to fix the SIGSEGV issue: #430

**Comment by mareklibra** [comment]
ATM, the CI is passing with and without #430 . So it LGTM.

**We will need to monitor flakiness.**

**Review by flaper87 — APPROVED** [review]
/approve

**Pull request merged**
