### PR TITLE
Fix hub config in cases where disconnected registry was not installed

### PR DESCRIPTION
**Pull request by loganmc10**
# Description

Right now, if you skip the deploy-disconnected-registry step, the hub pipeline does not complete successfully. This PR modifies the deploy-hub-configs step to check for the registry namespace (ztpfw-registry).

If the registry namespace does not exist, it is assumed to be a connected install, so 01_Mirror_ConfigMap.yml isn't deployed, and mirrorRegistryRef is not set in 04-agent-service-config.yml

Additionally, 02-cluster_imageset.yml is set to point to quay.io, rather than the disconnected registry.

Our eventual use case is to use an external disconnected registry (rather than connected or a disconnected registry on the hub). This is the first step, just to unblock us and allow the install to complete in a connected situation.

## Type of change

Please select the appropriate options:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [x] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by loganmc10** [comment]
hi @flaper87 can you please take a look at this? We aren't planning on using the integrated disconnected registry, we have an external (already existing) disconnected registry. This allows the pipeline to complete without the integrated registry.

We'll add our own task to the end of our pipeline to create a mirrorRegistryRef and ClusterImageSet that points to our registry.

**Comment by flaper87** [comment]
Thanks for the contribution, @loganmc10 

@achuzhoy any chance we can do a quick run of this PR to make sure your workflows are not broken?

**Comment by achuzhoy** [comment]
@flaper87 tested it with  a single NIC node for spoke. Both pipelines (hub/edge) completed fine. The same api flakiness exists.

**Comment by flaper87** [comment]
> @flaper87 tested it with a single NIC node for spoke. Both pipelines (hub/edge) completed fine. The same api flakiness exists.

this has nothing to do with the MetalLB issue so it's expected to be there.

**Comment by flaper87** [comment]
> Additionally, 02-cluster_imageset.yml is set to point to quay.io, rather than the disconnected registry.

I just noticed this comment. note that this is correct and the magic happens under-the-hood with the ICSPs. That said, we have changed it in main to point to the mirrored image.

**Review by flaper87 — APPROVED** [review]
note that this will have to be backported to the `1.13` branch so that we can then cut a new tag

**Pull request merged**
