### PR TITLE
Change naming from OCS to ODF

### PR DESCRIPTION
**Pull request by iranzo**
# Description

Change naming from OCS to ODF

Supersedes #212

### CODE REVIEW

**Comment by iranzo** [comment]
Tested on node 6

**Comment by alknopfler** [comment]
Which are the result for the test on flavio6? Everything ok? without errors?

**Comment by iranzo** [comment]
Server and spoke got deployed as well as worker !

**Comment by iranzo** [comment]
~~~
[detach-cluster : detach-cluster] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                                                                                                                                    [400/1889]
[detach-cluster : detach-cluster] Creating /workspace/ztp/build/spokes.yaml from SPOKES_CONFIG                                                                                                                    
[detach-cluster : detach-cluster] >>>> Dettaching clusters                                                                                                                                                        
[detach-cluster : detach-cluster] >>>>>>>>>>>>>>>>>>>>>>>>                                                                                                                                                        
[detach-cluster : detach-cluster] >> Cluster: spoke0-cluster                                                                                                                                                      
[detach-cluster : detach-cluster] >>>> Check spoke cluster: spoke0-cluster                                                                                                                                        
[detach-cluster : detach-cluster] >> Check ManagedCluster for spoke: spoke0-cluster                                                                                                                               
[detach-cluster : detach-cluster] ManagedCluster for spoke0-cluster condition: ManagedClusterConditionAvailable verified                                                                                          
[detach-cluster : detach-cluster] ManagedCluster for spoke0-cluster condition: ManagedClusterImportSucceeded verified                                                                                             
[detach-cluster : detach-cluster] ManagedCluster for spoke0-cluster condition: ManagedClusterJoined verified                                                                                                      
[detach-cluster : detach-cluster] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>                                                                                                                                   
[detach-cluster : detach-cluster] RSA Key-pair recovered!                                                                                                                                                         
[detach-cluster : detach-cluster] >> Recovering Spoke spoke0-cluster cluster Files                                                                                                                                
[detach-cluster : detach-cluster] # kubeconfig                                                                                                                                                                    
[detach-cluster : detach-cluster] # raw-kubeconfig                                                                                                                                                                
[detach-cluster : detach-cluster] # password                                                                                                                                                                      
[detach-cluster : detach-cluster] # username                                                                                                                                                                      
[detach-cluster : detach-cluster] serviceaccount/ztpfw-csr-approver created                                                                                                                                       
[detach-cluster : detach-cluster] clusterrole.rbac.authorization.k8s.io/ztpfw-csr-approver created                                                                                                                
[detach-cluster : detach-cluster] clusterrole.rbac.authorization.k8s.io/ztpfw-csr-approver added: "ztpfw-csr-approver"                                                                                            
[detach-cluster : detach-cluster] Error from server (NotFound): serviceaccounts "ztpfw-csr-approver" not found                                                                                                    
[detach-cluster : detach-cluster]                                                                                                                                                                                 
[detach-cluster : detach-cluster] Master Node: 1                                                                                                                                                                  
[detach-cluster : detach-cluster] AGENT: 2b7a8efc-3b20-41c0-b72a-9663b4ebce63                                                                                                                                     
[detach-cluster : detach-cluster] BMC: ee:ee:ee:ee:10:1e                                                                                                                                                          
[detach-cluster : detach-cluster] IP: 192.168.150.48                                                                                                                                                              
[detach-cluster : detach-cluster] >>>>                                                                                                                                                                            
[detach-cluster : detach-cluster] Copying source files: /workspace/ztp/spoke0-cluster/ztpfw-csr-approver-config to Node 192.168.150.48                                                                            
[detach-cluster : detach-cluster]                                                                                                                                                                                 
[detach-cluster : detach-cluster] Master Node: 0                                                                                                                                                                  
[detach-cluster : detach-cluster] AGENT: 306cd5f0-bd7a-4ea0-b49c-6bac94915a97                                                                                                                                     
[detach-cluster : detach-cluster] BMC: ee:ee:ee:ee:00:0e                                                                                                                                                          
[detach-cluster : detach-cluster] IP: 192.168.150.145                                                                                                                                                             
[detach-cluster : detach-cluster] >>>>                                                                                                                                                                            
[detach-cluster : detach-cluster] Copying source files: /workspace/ztp/spoke0-cluster/ztpfw-csr-approver-config to Node 192.168.150.145                                                                           
[detach-cluster : detach-cluster]                                                                                                                                                                                 
[detach-cluster : detach-cluster] Master Node: 2                                                                                                                                                                  
[detach-cluster : detach-cluster] AGENT: ae3e6b5b-8340-4638-acd7-289f768325f4                                                                                                                                     
[detach-cluster : detach-cluster] BMC: ee:ee:ee:ee:20:2e                                                                                                                                                          
[detach-cluster : detach-cluster] IP: 192.168.150.204                                                                                                                                                             
[detach-cluster : detach-cluster] >>>>                                                                                                                                                                            
[detach-cluster : detach-cluster] Copying source files: /workspace/ztp/spoke0-cluster/ztpfw-csr-approver-config to Node 192.168.150.204                                                                           
[detach-cluster : detach-cluster] >>>> Creating spoke cluster Keypair on Hub and Spoke spoke0-cluster                                                                                                             
[detach-cluster : detach-cluster] >> Secret name: spoke0-cluster-keypair                                                                                                                                          
[detach-cluster : detach-cluster] >> Namespace: spoke0-cluster                                                                                                                                                    
[detach-cluster : detach-cluster] secret/spoke0-cluster-keypair created                                                                                                                                           
[detach-cluster : detach-cluster] secret/cluster-ssh-keypair created 
~~~

**Comment by iranzo** [comment]
~~~
openshift-storage                                  csi-cephfsplugin-provisioner-fcfb44c89-slskp                      6/6     Running     33 (4h35m ago)   13h
openshift-storage                                  csi-cephfsplugin-prv4d                                            3/3     Running     0                14h
openshift-storage                                  csi-rbdplugin-gwm8z                                               3/3     Running     0                14h
openshift-storage                                  csi-rbdplugin-l2bzp                                               3/3     Running     0                14h
openshift-storage                                  csi-rbdplugin-mhdvp                                               3/3     Running     0                14h
openshift-storage                                  csi-rbdplugin-provisioner-7d96f8b4d5-k5l6b                        6/6     Running     29 (54m ago)     13h
openshift-storage                                  csi-rbdplugin-provisioner-7d96f8b4d5-k7fvx                        6/6     Running     32 (4h5m ago)    12h
openshift-storage                                  noobaa-core-0                                                     1/1     Running     0                12h
openshift-storage                                  noobaa-db-pg-0                                                    1/1     Running     0                13h
openshift-storage                                  noobaa-endpoint-765c8598c-vxxq7                                   1/1     Running     0                12h
openshift-storage                                  noobaa-operator-6596b88f6f-tqg5t                                  1/1     Running     0                13h
openshift-storage                                  ocs-metrics-exporter-769c9d4dfc-xt79k                             1/1     Running     0                13h
openshift-storage                                  ocs-operator-5cc8967fbb-s2m6p                                     1/1     Running     20 (4h5m ago)    13h
openshift-storage                                  rook-ceph-crashcollector-ztpfw-spoke0-cluster-master-0-69cqg58h   1/1     Running     0                13h
openshift-storage                                  rook-ceph-crashcollector-ztpfw-spoke0-cluster-master-1-bf6sdgw6   1/1     Running     0                12h
openshift-storage                                  rook-ceph-crashcollector-ztpfw-spoke0-cluster-master-2-6c96rpvs   1/1     Running     0                12h
openshift-storage                                  rook-ceph-mds-ocs-storagecluster-cephfilesystem-a-54c7d7f4q7bvt   2/2     Running     0                12h
openshift-storage                                  rook-ceph-mds-ocs-storagecluster-cephfilesystem-b-8454f6b8vrr7n   2/2     Running     0                13h
openshift-storage                                  rook-ceph-mgr-a-78d9ff5976-mgk6j                                  2/2     Running     0                12h
openshift-storage                                  rook-ceph-mon-a-5f995fbd87-fkd5c                                  2/2     Running     0                13h
openshift-storage                                  rook-ceph-mon-b-5b4fc594b7-7nbnq                                  2/2     Running     0                12h
openshift-storage                                  rook-ceph-mon-c-8f5bf54-9jnsn                                     2/2     Running     0                13h
openshift-storage                                  rook-ceph-operator-7997679cc4-4xxlq                               1/1     Running     0                13h
openshift-storage                                  rook-ceph-osd-0-55dd7654cd-9cqsp                                  2/2     Running     0                13h
openshift-storage                                  rook-ceph-osd-1-948f69b7c-g5chw                                   2/2     Running     0                12h
openshift-storage                                  rook-ceph-osd-10-856d57ffd9-rgrmr                                 2/2     Running     0                12h
openshift-storage                                  rook-ceph-osd-11-869cbc4865-nmt2x                                 2/2     Running     0                12h
openshift-storage                                  rook-ceph-osd-2-f96b6745b-2rb4h                                   2/2     Running     0                12h
openshift-storage                                  rook-ceph-osd-3-6d77678449-cn6fm                                  2/2     Running     0                12h
openshift-storage                                  rook-ceph-osd-4-8bf458c7b-crgl5                                   2/2     Running     0                13h
openshift-storage                                  rook-ceph-osd-5-8cbf4c54-7f9ww                                    2/2     Running     0                13h
openshift-storage                                  rook-ceph-osd-6-6999589cf6-7d4lz                                  2/2     Running     0                13h
openshift-storage                                  rook-ceph-osd-7-8476fcdd6b-fp97n                                  2/2     Running     0                13h
openshift-storage                                  rook-ceph-osd-8-74c96646bd-d74cb                                  2/2     Running     0                12h
openshift-storage                                  rook-ceph-osd-9-7bdc6b7fc9-4jf2d                                  2/2     Running     0                13h


~~~

**Comment by iranzo** [comment]
Merging after successful pipeline runs in node6

**Pull request merged**
