### PR TITLE
add the verify step to the metallb job

### PR DESCRIPTION
**Pull request by alknopfler**
Signed-off-by: Alberto Morgante Medina <alknopfler@users.noreply.github.com>

# Description

With this feature, we're able to re-run some steps in the spoke workflow. Now, there is not a step to verify so we cannot re-run the workflow because metallb will be failed. This PR fix this issue adding a verify step as well as the logic to make easy the verification.

Fixes # [MGMT-9902](https://issues.redhat.com/browse/MGMT-9902)

## Type of change

Please select the appropriate options:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A -> Tested locally cnf12
- [ ] Test B

**Test Configuration**:

- Versions: 4.9
- Hardware:  cnf12(worker0)

## Checklist

- [x] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [x] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [x] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Review by flaper87 — DISMISSED** [review]
commented but that can be done in a follow up pr.

/lgtm

**Review by jparrill — DISMISSED** [review]
LGTM

**Review by jparrill — APPROVED** [review]
LGTM

**Review by danielchg — APPROVED** [review]

**Pull request merged**
