### PR TITLE
MGMT-10246: Suport custom-provided TLS certificates

### PR DESCRIPTION
**Pull request by mareklibra**
# Description

The user can upload TLS certificates per domain instead of generating self-signed ones.

TODO:
- [x] Certs on the Settings page
- [x] Try in non-dev env - blocked on https://bugzilla.redhat.com/show_bug.cgi?id=2082539
- [x] Contribute Patternfly for ReactNode type for ExpandableSection's `toggleText` property 
  - filing RFE [1171](https://github.com/patternfly/patternfly-design/issues/1171) - contribution will take long and we can workaround
- [ ] decide `isAutomatic` in `SettingsPageDomainCertificates.tsx`
- [x] certificate-content check in `ui/frontend/src/components/utils.ts`

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by fbac** [comment]
@mareklibra same as with the other PR, this seems to be a stale change. Is it currently needed? Is there something missing or where we can work on or help you with?

**Comment by mareklibra** [comment]
@fbac Yes, this is needed and work is still in progress.

**Review by alknopfler — APPROVED** [review]
LGTM

**Review by flaper87 — APPROVED** [review]
let's get this baby in! :muscle:

**Pull request merged**
