### PR TITLE
Fix: metallb order patch

### PR DESCRIPTION
**Pull request by alknopfler**
# Description

fix to change the order to metallb patch 

Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2106840

Previous PR: https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/pull/469

## Type of change

Please select the appropriate options:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

change the metallb patch order to solve the issue with serviceaccount

image

- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Review by flaper87 — APPROVED** [review]
TEsted on single NIC SNO

**Comment by flaper87** [comment]
This needs to be backproted to `stable-1.10`

**Comment by flaper87** [comment]
@alknopfler please, refer to the metallb bugzilla and link the previous PR that this one is fixing.

**Review by danielchg — APPROVED** [review]
LGTM

**Pull request merged**
