### PR TITLE
Adding a workaround for https://issues.redhat.com/browse/MGMT-11935

### PR DESCRIPTION
**Pull request by achuzhoy**
The policy.json file is set to promiscuous mode.

Signed-off-by: Alexander Chuzhoy <achuzhoy@redhat.com>

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please select the appropriate options:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change is a documentation update

## Testing

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Versions:
- Hardware:

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

### CODE REVIEW

**Comment by achuzhoy** [comment]
cc @flaper87

**Comment by achuzhoy** [comment]
successfully tested this workaround on 2 nodes.

**Comment by achuzhoy** [comment]
The pipelines fail without it (had my deployments failing for days).
This is a temporary workaround - to get us unblocked.

The issue is similar to https://bugzilla.redhat.com/show_bug.cgi?id=2073197

**Review by alknopfler — APPROVED** [review]
LGTM

**Comment by flaper87** [comment]
/hold

I want to take some time to dive into this a bit more.

**Comment by jparrill** [comment]
Hey folks, IMHO I don't recommend to follow this "disable security" path. I prefer this approach: https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#a-reasonably-locked-down-system where you can specify the "allowedAll" for certain mirrors.

**Comment by flaper87** [comment]
> Hey folks, IMHO I don't recommend to follow this "disable security" path. I prefer this approach: https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md#a-reasonably-locked-down-system where you can specify the "allowedAll" for certain mirrors.

Thanks @jparrill !

Let's see if the test with `ubi8` helps with this issue, otherwise we will have to craft a more specific policy.json for the ztpfw image

**Comment by flaper87** [comment]
Closing as we migrated to `ub8` as base image which seems to solve this issue

**Pull request closed without merging**
